/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JBDT;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class JBDTTest {
    @Test public void testAppHasAGreeting() {
        JBDT classUnderTest = new JBDT();
        assertNotNull("app should have a greeting", classUnderTest.test());
    }
}
